### PR TITLE
Weather javascript

### PR DESCRIPTION
**Pull request by 2419746**
Will add Javascript to make the info go into cards later.  Unsure how the date time search will work with this api but will try have a look tomorrow

### CODE REVIEW

**Comment by 2419746** [comment]
Looking into using a different api for this

**Comment by 2419746** [comment]
Using a different api for this now but i think this will still need merged first for the html changes

**Review by AdamCMunro — APPROVED** [review]
awesome work

**Review by AndrewLeinster — APPROVED** [review]
Great work, thanks Laura!

**Pull request merged**
